= Maven Plugin Integration Testing (Level 0)
:author: Karl Heinz Marbaise
:email: khmarbaise@apache.org
:revnumber: 0.1.0
:sectnums:
:toc:

:maven-plugins: https://maven.apache.org/plugins/[Maven Plugins]
:maven-failsafe-plugin: https://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin]


== Overview (Level 1)
The expressiveness of tests is a very important part of writing integration tests or
test in general. If a test is not easy to understand a test it very likely not being written.

Lets take a look into the following code which gives you an impression how an integration
test for a {maven-plugins}/Maven Extensions/Maven-Core should look like:

[source,java]
----
package org.it;

import static org.assertj.core.api.Assertions.assertThat;

import org.apache.maven.jupiter.extension.MavenIT;
import org.apache.maven.jupiter.extension.MavenTest;
import org.apache.maven.jupiter.extension.maven.MavenExecutionResult;

@MavenIT
class FirstMavenIT {

  @MavenTest
  void the_first_test_case(MavenExecutionResult result) {
    assertThat(result)
      .build()
        .isSuccessful()
      .and()
      .project()
        .hasTarget()
          .withEarFile()
            .containsOnlyOnce("META-INF/MANIFEST.MF")
        .log()
          .info().contains("Writing data to file")
      .cache()
          .withEarFile("G:A:V")
          .withPomFile("G:A:V")
          .withMetadata().contains("xxx");
  }
}
----

== Convention over Configuration Paradigm (Level 1)

The location of the above integration test defaults to `src/test/java/<package>/FirstMavenIT.java`.
The selected name like `*IT.java` implies that it will be executed by {maven-failsafe-plugin} by convention.
This will result in a directory structure as follows:
[source,text]
----
src
 +- test
     +- java
          +- org
              +- it
                 +- FirstIT.java
----
Defining integration tests we need also projects which are the *test cases*. This needs
to be put somewhere in the directory tree to be easily associated with the test `FirstMavenIT`.

The project to be used as an test case is implied to be located into
`src/test/resources-its/<package>/FirstMavenIT` this looks like this:

[source,text]
----
src
 +- test
     +- resources-its
          +- org
              +- it
                 +- FirstIT
----
But now where to put the separated *test cases*? This can easily achieved by using the
*method name*  within the test class which is `the_first_test_case` in our example. This results
in the following directory layout:

[source,text]
----
src
 +- test
     +- resources-its
          +- org
              +- it
                 +- FirstIT
                     +-- the_first_test_case
----

This approach solves the issue having several test cases within a single test class which is a usual
way to write tests.



//-



* The header in AsciiDoc must start with a document title.
+
----
= Document Title
----
+
Keep in mind that the header is optional.

* Optional Author and Revision information immediately follows the header title.
+
----
= Document Title
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
----

Here we continue the text.
Here we continue the text.
Here we continue the text.
Here we continue the text.

* The header in AsciiDoc must start with a document title.
+
--
Here's an example of a document title:

----
= Document Title
----

NOTE: The header is optional.
--

.TODO List
* [ ] Document
* [ ] More
* [ ] More
* [ ] More
* [ ] More

