= Maven Integration Testing Users Guide
:author: Karl Heinz Marbaise
:email: khmarbaise@apache.org
:revnumber: 0.1.0
:sectnums:
:toc:

:junit-jupiter: https://junit.org/junit5/[JUnit Jupiter]

:maven-invoker-plugin: https://maven.apache.org/plugins/maven-invoker-plugin[Maven Invoker Plugin]
:maven-plugins: https://maven.apache.org/plugins/[Maven Plugins]
:maven-failsafe-plugin: https://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe Plugin]
:mock-repository-manager: https://www.mojohaus.org/mrm/index.html[Mock Repository Manager]

== Basics

This integration test framework is an extension for {junit-jupiter}. The usage of JUnit Jupiter
already gives a lot of support for things are very useful in case of writing unit- and integration
tests.

== Status

The current status of this extension is experimental.

== Overview
The expressiveness of tests is a very important part of writing integration tests or
test in general. If a test is not easy to understand it is very likely not being written.

Lets take a look into the following code example which gives you an impression how an integration
test for a {maven-plugins}/Maven Extensions/Maven-Core should look like:

//FIXME: There are several details which are not yet clear how to solve them?
[source,java]
----
package org.it;

import static org.assertj.core.api.Assertions.assertThat;

import org.apache.maven.jupiter.extension.MavenIT;
import org.apache.maven.jupiter.extension.MavenTest;
import org.apache.maven.jupiter.extension.maven.MavenExecutionResult;

@MavenIT
class FirstMavenIT {

  @MavenTest
  void the_first_test_case(MavenExecutionResult result) {
    assertThat(result).build().isSuccessful();
  }

}
----

The above used assertions like `assertThat(..)` are custom assertions which will be explained in
later chapters
//FIXME: link to chapter for assertions.

== Structuring Integration Tests

=== A Single Test Case
The location of an integration test defaults to `src/test/java/<package>/FirstMavenIT.java`.
The selected naming schema like `<any>IT.java` implies that it will be executed by {maven-failsafe-plugin}
by convention. This will lead us in a directory structure as follows:
[source,text]
----
.
└── src/
    └── test/
        └── java/
            └── org/
                └── it/
                    └── FirstMavenIT.java
----
In case of an integration test for a Maven plugin/extension or others we need to be able to
define also the projects which are the *real test cases* (Maven projects).
This needs to be put somewhere in the directory tree to be easily associated with the given
test `FirstMavenIT`.

The project to be used as an test case is implied to be located into
`src/test/resources-its/<package>/FirstMavenIT` this looks like this:
//TODO: should we keep the location `resources-its` ?
[source,text]
----
.
└── src/
    └── test/
        └── resources-its/
            └── org/
                └── it/
                    └── FirstMavenIT/
----
Currently this location is separated from all other resources directories to make filtering easier
which has to be configured within your `pom.xml` file and preventing interfering with other
configurations.

We have an integration test class for example `FirstMavenIT` but what if we like to write several
test cases? So we need to make separation between different *test cases* which can be achieved by
using the *method name* within the test class `FirstMavenIT` which is `the_first_test_case` in our
example. This results in the following directory layout:

[source,text]
----
.
└── src/
    └── test/
        └── resources-its/
            └── org/
                └── it/
                    └── FirstMavenIT/
                        └── the_first_test_case/
                            ├── src/
                            └── pom.xml
----
This approach gives us the opportunity to write several integration test cases within a
single test class `FirstMavenIT` and also separates them easily.
The usage of the *method name* implies some limitations based on the naming rules for *method names*.
The best practice is to write *method names* with lowercase letters and separate words by using an
underscore `_`. This will prevent issues with case insensitive file systems.

=== Test Case Execution

During the execution of the integration tests the following directory structure will be created
within the `target` directory:
[source,text]
----
.
└──target/
   └── maven-its/
       └── org/
           └── it/
               └── FirstMavenIT/
                   └── the_first_test_case/
                       ├── .m2/
                       ├── project/
                       │   ├── src/
                       │   ├── target/
                       │   └── pom.xml
                       ├── mvn-stdout.log
                       ├── mvn-stderr.log
                       └── other logs
----
Based on the above you can see that each *test case* (method within the test class `FirstMavenIT`)
has it's own local repository (aka local cache) `.m2/repository`. Furthermore you see that the
project is built within the `project` directory. This gives you a view of the built project as you
did on plain command line and take a look into it. The output of the built is written into
`mvn-stdout.log` (stdout) and the output to stderr is written to `mvn-stderr.log`.
//TODO: Define `other logs` ? environment output, command line parameters ?
//FIXME: Needs to be implemented

=== Several Test Cases
If we like to define several integration test cases within a single test class `SeveralMavenIT`
we have to define different methods which are the test cases. This results in the following
class layout:
[source,java]
----
package org.it;

import static org.assertj.core.api.Assertions.assertThat;

import org.apache.maven.jupiter.extension.MavenIT;
import org.apache.maven.jupiter.extension.MavenTest;
import org.apache.maven.jupiter.extension.maven.MavenExecutionResult;

@MavenIT
class SeveralMavenIT {

  @MavenTest
  void the_first_test_case(MavenExecutionResult result) {
     ...
  }
  @MavenTest
  void the_second_test_case(MavenExecutionResult result) {
     ...
  }
  @MavenTest
  void the_third_test_case(MavenExecutionResult result) {
     ...
  }
}
----
The structure for the Maven projects which are used by each of the test cases (*method names*)
looks like the following:
[source,text]
----
.
└── src/
    └── test/
        └── resources-its/
            └── org/
                └── it/
                    └── SeveralMavenIT/
                        ├── the_first_test_case/
                        │   ├── src/
                        │   └── pom.xml
                        ├── the_second_test_case/
                        │   ├── src/
                        │   └── pom.xml
                        └── the_this_test_case/
                            ├── src/
                            └── pom.xml
----
After running the integration tests the resulting directory structure in the `target`
directory will look like this:
[source,text]
----
.
└──target/
   └── maven-its/
       └── org/
           └── it/
               └── SeveralMavenIT/
                   ├── the_first_test_case/
                   │   ├── .m2/
                   │   ├── project/
                   │   │   ├── src/
                   │   │   ├── target/
                   │   │   └── pom.xml
                   │   ├── mvn-stdout.log
                   │   ├── mvn-stderr.log
                   │   └── other logs
                   ├── the_second_test_case/
                   │   ├── .m2/
                   │   ├── project/
                   │   │   ├── src/
                   │   │   ├── target/
                   │   │   └── pom.xml
                   │   ├── mvn-stdout.log
                   │   ├── mvn-stderr.log
                   │   └── other logs
                   └── the_third_test_case/
                       ├── .m2/
                       ├── project/
                       │   ├── src/
                       │   ├── target/
                       │   └── pom.xml
                       ├── mvn-stdout.log
                       ├── mvn-stderr.log
                       └── other logs
----
Based on the structure you can exactly dive into each test case separately and take
a look at the console output of the test case via `mvn-stdout.log` or maybe in case of errors
in the `mvn-stderr.log`. In the `project` directory you will find the usual `target` directory
which contains the Maven output which might be interesting as well. Furthermore the
local cache (aka maven repository) is available separately for each test case and can be found
in the `.m2/repository` directory.

== Scenarios

=== Grouping Test Cases
Sometimes it makes sense to group test into different groups together. This can be achieved
via the `@Nested` annotation which is provided by {junit-jupiter}. This would result in
a test class like this:
[source,java]
.MavenIntegrationGroupingIT.java
----
@MavenIT
class MavenIntegrationGroupingIT {

  @MavenTest
  void packaging_includes(MavenExecutionResult result) {
  }

  @Nested
  class NestedExample {

    @MavenTest
    void basic(MavenExecutionResult result) {
    }

    @MavenTest
    void packaging_includes(MavenExecutionResult result) {
    }

  }
}
----
After test execution the resulting directory tree looks like this:
[source,text]
----
.
└──target/
   └── maven-its/
       └── org/
           └── it/
               └── MavenIntegrationGroupingIT/
                   ├── packaging_includes/
                   │   ├── .m2/
                   │   ├── project/
                   │   │   ├── src/
                   │   │   ├── target/
                   │   │   └── pom.xml
                   │   ├── mvn-stdout.log
                   │   ├── mvn-stderr.log
                   │   └── other logs
                   └── NestedExample/
                       ├── basic/
                       │   ├── .m2/
                       │   ├── project/
                       │   │   ├── src/
                       │   │   ├── target/
                       │   │   └── pom.xml
                       │   ├── mvn-stdout.log
                       │   ├── mvn-stderr.log
                       │   └── other logs
                       └── packaging_includes/
                           ├── .m2/
                           ├── project/
                           │   ├── src/
                           │   ├── target/
                           │   └── pom.xml
                           ├── mvn-stdout.log
                           ├── mvn-stderr.log
                           └── other logs
----


=== Common Maven Cache

In all previous test case examples the maven cache (aka maven repository)
is created separately for each of the test cases (*test methods*). There are times
where you need to have a common cache (aka maven repository) for two or more test
cases together. This can be achieved easily via the `@MavenRepository` annotation.
The usage looks like the following:

[source,java]
.MavenIntegrationExampleNestedGlobalRepoIT.java
----
package org.it;

import org.apache.maven.jupiter.extension.MavenIT;
import org.apache.maven.jupiter.extension.MavenRepository;
import org.apache.maven.jupiter.extension.MavenTest;
import org.apache.maven.jupiter.extension.maven.MavenExecutionResult;

@MavenIT
@MavenRepository
class MavenITWithGlobalMavenCacheIT {

  @MavenTest
  void packaging_includes(MavenExecutionResult result) {
  }

  @MavenTest
  void basic(MavenExecutionResult result) {
  }

}
----

After test execution the resulting directory tree looks like this:
[source,text]
----
.
└──target/
   └── maven-its/
       └── org/
           └── it/
               └── MavenITWithGlobalMavenCacheIT/
                   ├── .m2/
                   ├── packaging_includes/
                   │   ├── project/
                   │   │   ├── src/
                   │   │   ├── target/
                   │   │   └── pom.xml
                   │   ├── mvn-stdout.log
                   │   ├── mvn-stderr.log
                   │   └── other logs
                   └── basic/
                       ├── project/
                       │   ├── src/
                       │   ├── target/
                       │   └── pom.xml
                       ├── mvn-stdout.log
                       ├── mvn-stderr.log
                       └── other logs
----

== Test Case Execution


Based on the given structure of directories etc. it is easy to run all test
cases in parallel which saves a lot of time.
This mean by default all the test cases are running in parallel.







== BACKUP AREA

[source,java]
.filename.java
----
    assertThat(result)
      .project()
        .hasTarget()
          .withEarFile()
            .containsOnlyOnce("META-INF/MANIFEST.MF");

    assertThat(result)
      .project()
        .log()
          .info().contains("Writing data to file");

    assertThat(result)
      .cache()
          .hasEarFile("G:A:V")
          .hasPomFile("G:A:V")
          .hasMetadata("G:A")
            .contains("xxx");
----


